import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillLinkedin, AiFillGithub, AiFillTwitterCircle} from "react-icons/ai"
import Image from 'next/image'
import Avatar from '../public/avatar.png'
import Cards from './components/Cards'

export default function Home() {
  return (
    <>
      <Head>
        <title>Anfal Ibrahim | Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-6'>
        <section className='min-h-max'>
          <nav className='py-10 px-10 mb-12 flex justify-between items-center  '>
            <h1 className='text-xl font-sunny'>
              Anfal Ibrahim | Web Dev
            </h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill className='cursor-pointer text-2xl'/>
              </li>
              <li>
                <a href='#' className=' bg-gradient-to-r from-cyan-500 to-teal-300 text-white px-4 py-2 rounded-md ml-6'>Resume</a>
              </li>
            </ul>
          </nav>
          <div className='text-center p-10 '>
            <h2 className='text-3xl p-2 font-medium  '>Anfal Ibrahim</h2>
            <h3 className='text-2xl p-2'>
              Web Developer
            </h3>
            <p className='text-md py-5 leading-2 text-slate-600 '>
             &quot;When you feel like giving up, remember why you started.&quot;
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-8 text-slate-600 py-3'>
            <AiFillGithub/>
            <AiFillLinkedin />
            <AiFillTwitterCircle />
          </div>
          <div className='relative bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-10 mx-auto overflow-hidden'>
            <Image src={Avatar} alt='avatar' layout='fill' objectFit='cover'/>
          </div>
        </section>
        
        <section>
          <div className='text-center my-10 md:text-left md:px-10 '>
            <h3 className='text-2xl p-2'>
              About me
            </h3>
            <p className='text-md py-5 leading-2 text-slate-600'>
              As a web developer, I have skills in designing, developing and maintaining responsive and interactive websites. I am skilled in programming languages such as HTML, CSS and JavaScript and have knowledge in web frameworks such as React.
            </p>
            <p className='text-md py-5 leading-2 text-slate-600'>
              Apart from that, I am also familiar with managing databases and using server-side programming languages such as Node.js. I always pay attention to website security and performance and put a high priority on a good user experience.
            </p>
          </div>
        </section>
        <Cards />
      </main>
    </>
  )
}
